# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "nan-2.16.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.16.0.tgz";
        sha512 = "UdAqHyFngu7TfQKsCBgAA6pWDkT8MAO7d0jyOecVhN5354xbLqdn8mV9Tat9gepAupm0bt2DbeaSC8vS52MuFA==";
      };
    };
    "node-postal-1.1.2" = {
      name = "node-postal";
      packageName = "node-postal";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-postal/-/node-postal-1.1.2.tgz";
        sha512 = "eWg/p0dgDuPZT55kYnoZASDRfmXHGirGKtWwDprZSJklHhlnEuYfc62JF2mxVE6A7N6KV1vb49DJTvqdL/K/Xg==";
      };
    };
  };
  args = {
    name = "postal-test";
    packageName = "postal-test";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."bindings-1.5.0"
      sources."file-uri-to-path-1.0.0"
      sources."nan-2.16.0"
      sources."node-postal-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
